[package]
name = "scop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.11"
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
winit = {  version = "0.30.0", features = ["rwh_05"]}
